version: "3.3"

services:
  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skull_king
      MYSQL_USER: mermaid
      MYSQL_PASSWORD: beats_the_skull_king
    networks:
      - skull_king

  redis:
    image: redis:6.0.5
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - skull_king

  # api:
  #   build:
  #     context: ../SkullKing-API
  #     dockerfile: ../SkullKing-Docker/api/Dockerfile
  #   restart: unless-stopped
  #   command: npm run start:dev
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ../SkullKing-API:/usr/src/app
  #     - /usr/src/app/node_modules/
  #     # - /usr/src/app/dist/
  #   networks:
  #     - skull_king

  # react:
  #   build:
  #     context: ../SkullKing
  #     dockerfile: ../SkullKing-Docker/react/Dockerfile
  #   restart: unless-stopped
  #   command: yarn start
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - ../SkullKing:/usr/src/app
  #     - /usr/src/app/node_modules/
  #   networks:
  #     - skull_king

networks:
  skull_king:
    name: skull_king
